id: P001793
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:21:58.671170
source_metadata:
  id: bdr:W4CZ74499
  title: ཀུན་རིག་དང་རྟ་མགྲིན་གསང་སྒྲུབ་ཀྱི་སྒྲུབ་སྐོར་སོགས།
  author: ''
  volumes:
    92c1e7e60d454125ba0fb615afe5a608:
      image_group_id: I4CZ74501
      title: ''
      volume_number: 1
      total_pages: 714
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
