id: I72A810B7
legacy_id: P001793
ocr_import_info:
  bdrc_scan_id: W4CZ74499
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T21:17:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:09:29.265132+00:00'
last_modified: 2022-09-04 05:09:47.466356
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74499
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74499
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་རིག་དང་རྟ་མགྲིན་གསང་སྒྲུབ་ཀྱི་སྒྲུབ་སྐོར་སོགས།
statistics:
  ocr_word_mean_confidence_index: 0.496252902392519
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I4CZ74501:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74501
      total_pages: 714
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74501.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.496252902392519
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
